# Generated by Django 5.1.1 on 2024-10-02 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='çhoice',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='qustion_text',
        ),
    ]
