# Generated by Django 5.1.1 on 2024-10-02 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choice_çhoice_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='çhoice',
            new_name='Choice',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='qustion_text',
            new_name='question_text',
        ),
    ]
